<%= fetch(:stage) %>:
  adapter: mysql2
  encoding: utf8
  host: <%= fetch(:secrets)[fetch(:stage)]['mysql_host'] %>
  port: 3306
  database: crema
  username: crema
  password: <%= ENV['CREMA_MYSQL_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  collation: utf8_general_ci